#!/sbin/sh

# Replaces 'delete DATA:miui' in update-script.
# Fixes issue caused when /data/miui is apps2sd symlink.

find_cmd=`find data -name app -type l -maxdepth 1`

if [ "$find_cmd" != "" ]
then
  chmod 777 /data/miui
  rm -f /data/miui
fi
